### ISSUE TITLE
文档的元音前面写了a。

### ISSUE THREAD

**Issue by oilel** [ssrlive/socks5-impl#4]
https://docs.rs/socks5-impl/latest/socks5_impl/server/struct.Server.html 这里写了“or be created on a existing TcpListener”，但是existing开头是元音，左边应该是an。

**Comment by ssrlive** [comment]
已改，感谢捉虫。

**Comment by oilel** [comment]
https://docs.rs/socks5-impl/latest/socks5_impl/server/connection/struct.IncomingConnection.html 这里还有一个A Incoming。 @ssrlive
